service: pin-reporting-node

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  stackName: pin-reporting-node
  role: arn:aws:iam::312226949769:role/lambda-sqs-s3-logs
  deploymentBucket:
    name: s3-pins
  vpc:
    securityGroupIds:
      - "sg-27f9af42"
    subnetIds:
      - "subnet-96d526e1"
      - "subnet-c69c8aee"

functions:
  inventoryReport:
    handler: handler.inventoryReport
    events:
     - http:
         path: "/inventoryReport"
         method: get
    layers:
      - ${cf:oraclelib-layer-dev.OraclelibLayerExport}

package:
  exclude:
    - oraclelib-layer/**
    - '.*'
    - '.*/**'
    - '*.json'
